name: Unit Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.jpg'
      - '**/*.png'
      - '**/README.*'
      - '**/LICENSE.*'
      - 'docs/**'
      - 'ISSUE_TEMPLATE/**'

permissions:
  id-token: write
  contents: read

env:
  BUILD_CONFIG: Release

jobs:
  test-win-unit:
    name: Windows - Unit Test
    runs-on: windows-latest
    steps:
      - name: Checkout aws-advanced-odbc-wrapper
        uses: actions/checkout@v4
      - name: Retrieve AWS SDK for C++ Cache
        id: cache-aws-sdk-cpp
        uses: actions/cache@v4
        with:
          path: aws_sdk/install
          key: ${{ runner.os }}-aws-sdk-cpp-${{env.BUILD_CONFIG}}
      - name: Build AWS SDK for C++
        if: ${{steps.cache-aws-sdk-cpp.outputs.cache-hit != 'true'}}
        run: |
          ./scripts/compile_aws_sdk_win.ps1 Release
      - name: Build aws-advanced-odbc-wrapper
        run: |
          cmake -S . -B build -DBUILD_UNICODE=OFF -DBUILD_UNIT_TEST=ON
          cmake --build build --config Release
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: odbc-wrapper-win-unit
      - name: Run Unit Tests
        run: |
          ./build/test/unit_test/Release/unit-test.exe

  test-macos-unit:
    name: MacOS - Unit Test
    runs-on: macos-15
    steps:
      - name: Checkout aws-advanced-odbc-wrapper
        uses: actions/checkout@v4
      - name: Install Build Dependencies
        run: |
          brew update && brew upgrade && brew cleanup
          brew install cmake unixodbc postgresql curl openssl zlib
      - name: Retrieve AWS SDK for C++ Cache
        id: cache-aws-sdk-cpp
        uses: actions/cache@v4
        with:
          path: aws_sdk/install
          key: ${{ runner.os }}-aws-sdk-cpp-${{env.BUILD_CONFIG}}
      - name: Build AWS SDK for C++
        run: |
          ./scripts/compile_aws_sdk_unix.sh Release "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/"
      - name: Build aws-advanced-odbc-wrapper
        run: |
          cmake -S . -B build -DBUILD_UNICODE=OFF -DBUILD_UNIT_TEST=ON -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/
          cmake --build build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: odbc-wrapper-linux-unit
      - name: Run Unit Tests
        run: |
          ./build/test/unit_test/unit-test

  test-linux-unit:
    name: Linux Ubuntu - Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout aws-advanced-odbc-wrapper
        uses: actions/checkout@v4
      - name: Install Build Dependencies
        run: |
          sudo apt update
          sudo apt-get install cmake libcurl4-openssl-dev libssl-dev odbcinst unixodbc-dev uuid-dev zlib1g-dev
      - name: Retrieve AWS SDK for C++ Cache
        id: cache-aws-sdk-cpp
        uses: actions/cache@v4
        with:
          path: aws_sdk/install
          key: ${{ runner.os }}-aws-sdk-cpp-${{env.BUILD_CONFIG}}
      - name: Build AWS SDK for C++
        if: ${{steps.cache-aws-sdk-cpp.outputs.cache-hit != 'true'}}
        run: |
          ./scripts/compile_aws_sdk_unix.sh Release
      - name: Build aws-advanced-odbc-wrapper
        run: |
          cmake -S . -B build -DBUILD_UNICODE=OFF -DBUILD_UNIT_TEST=ON
          cmake --build build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: odbc-wrapper-macos-unit
      - name: Run Unit Tests
        run: |
          ./build/test/unit_test/unit-test
